GET http://localhost:8888/ebook/list?
Accept: application/json

###
POST http://localhost:8888/test
Content-Type: application/x-www-form-urlencoded

name=aini

###
GET http://localhost:8888/ebook/list?name=spring
Accept: application/json

###